export const qs2027 = [
  { rank: 1, name: "Massachusetts Institute of Technology (MIT)", country: "United States", code: "US", change: "—" },
  { rank: 2, name: "Imperial College London", country: "United Kingdom", code: "GB", change: "—" },
  { rank: 2, name: "Stanford University", country: "United States", code: "US", change: "+1" },
  { rank: 4, name: "University of Oxford", country: "United Kingdom", code: "GB", change: "—" },
  { rank: 5, name: "Harvard University", country: "United States", code: "US", change: "—" },
  { rank: 6, name: "University of Cambridge", country: "United Kingdom", code: "GB", change: "—" },
  { rank: 7, name: "California Institute of Technology (Caltech)", country: "United States", code: "US", change: "+3" },
  { rank: 8, name: "ETH Zurich", country: "Switzerland", code: "CH", change: "-1" },
  { rank: 8, name: "UCL", country: "United Kingdom", code: "GB", change: "+1" },
  { rank: 10, name: "National University of Singapore (NUS)", country: "Singapore", code: "SG", change: "-2" },
  { rank: 11, name: "The University of Hong Kong", country: "Hong Kong SAR", code: "HK", change: "—" },
  { rank: 12, name: "Nanyang Technological University, Singapore", country: "Singapore", code: "SG", change: "—" },
  { rank: 13, name: "Peking University", country: "China", code: "CN", change: "+1" },
  { rank: 14, name: "Tsinghua University", country: "China", code: "CN", change: "+3" },
  { rank: 15, name: "University of Pennsylvania", country: "United States", code: "US", change: "—" },
  { rank: 16, name: "Cornell University", country: "United States", code: "US", change: "—" },
  { rank: 16, name: "Yale University", country: "United States", code: "US", change: "+5" },
  { rank: 18, name: "The Chinese University of Hong Kong", country: "Hong Kong SAR", code: "HK", change: "+14" },
  { rank: 19, name: "The University of New South Wales", country: "Australia", code: "AU", change: "+1" },
  { rank: 20, name: "Johns Hopkins University", country: "United States", code: "US", change: "+4" },
  { rank: 20, name: "University of California, Berkeley (UCB)", country: "United States", code: "US", change: "-3" },
];

export const qsSource = "https://www.qs.com/insights/qs-world-university-rankings";
